### ISSUE TITLE
Empty GC lines should contain at least one space character

### ISSUE THREAD

**Issue by jmmelko** [nzhagen/zemaxglass#3]
Hi,

Trying to import lightpazth.gcf into VirtualStudio an error was generated:

Index was outside the bounds of the array.

I have solved this by adding a space (blank) character after the GC header.

I don't know what is the official practice, but it wouldn't hurt to add this.

I can fork and pull a  request if you like

**Comment by nzhagen** [comment]
Sorry for taking so long getting to this! I happened no to notice this was here until I worked on a different issue in this repo.

The files used by Zemax do not generally have this space character, and the Zemax manual itself does not specify requiring one, so this is possibly a quirk of how the VirtualStudio programmers chose to implement the format. However, adding said space is easy to do and has no effect on the existing codebase and so I've added the necessary spaces.
- Nathan
