### ISSUE TITLE
Incorrect Sellmeier2 Formula

### ISSUE THREAD

**Issue by drocheam** [nzhagen/zemaxglass#4]
According to the Zemax manual, page 333 (page 345 in the linked pdf), the second fraction of the Sellmeier2 equation has no wavelength dependence in the numerator.
This is different to your code as well as your manual.

Link:
https://documents.pub/document/zemaxmanual.html?page=345

**Comment by nzhagen** [comment]
Thanks for the tip! I have removed the wavelength dependence in the numerator, so this formula should be correct now.
- Nathan

**Comment by drocheam** [comment]
Thanks for looking over this.
However, your manual still has the old formula in it:
https://github.com/nzhagen/zemaxglass/blob/master/ZemaxGlass_user_manual.pdf

Furthermore, it seems you have removed the w**2 from the first fraction, not the second:
https://github.com/nzhagen/zemaxglass/commit/1f323e5bd154f13f65167b5970b766531fc5b242

**Comment by nzhagen** [comment]
Ah, yes, thanks! That was an annoyingly stupid mistake. I've updated the
new version, where the wavelength dependence is back in the first fraction,
but removed from the second fraction. I've also updated the manual to
reflect the change.

- Nathan
